name: API Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - name: Run API tests
        run: npm run test
        env:
          DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5433/test?schema=public
          DATABASE_URL_DIRECT: postgres://postgres:postgres@postgres:5432/test
